version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: frontend/frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3003:3003
